---

- name: Installation de nginx
  apt: name={{ item }} state=present cache_valid_time=3600
  with_items:
    - nginx-full
    - liblwp-useragent-determined-perl
    - unzip

- name: Créer repertoire default et erreur
  file: path=/var/www/{{ item }} state=directory owner=www-data group=www-data mode="u+rwX,g+rwX,o+r" recurse=yes
  with_items:
    - error
    - default

- name: Copie des fichier de nginx
  copy: src={{ item }} dest=/etc/nginx/{{ item }} owner=root group=root mode="u+rw,g+r,o+r"
  with_items:
    - nginx.conf
    - conf.d/stopforumspam.conf
    - sites-available/default
  notify:
    - restart nginx

- name: Copie default site et error
  copy: src=web/{{ item }} dest=/var/www/{{ item }} owner=www-data group=www-data mode="u+rw,g+r,o+r"
  with_items:
    - default/index.html
    - error/-error-404.html
    - error/-error-50x.html

- name: Tache cron spam
  cron: name="Update ban list nginx" minute="30" hour="0" job="/opt/tharyrok/stopforumspam/spam.sh"

- name: Activer le service nginx au démérage
  service: name=nginx state=started enabled=yes
