---
# confgig commun de tout les hosts

- hosts: mail.moss.lghs.space
  vars:
    DOMAIN:
      - lghs.space
      - lghs.be
      - ml.lghs.be

  pre_tasks:
    - include_vars: secured/password.yml

  roles:

    - letsencrypt
    - le-mail
    - dovecote
    - postfix
    - mlmmj
