---
# confgig general de tout les hosts

- name: Installation de collectd-core
  apt: name=collectd-core state=present cache_valid_time=3600

- name: Installation de rrdcached
  apt: name=rrdcached state=present cache_valid_time=3600
  when: ansible_hostname == "monit"

- name: rrdcached config
  replace: dest=/etc/default/rrdcached regexp='^#OPTS=""$' replace='OPTS="-l unix:/var/run/rrdcached.sock -j /var/lib/rrdcached/journal/ -F -B -b /var/lib/collectd/rrd"' backup=no
  when: ansible_hostname == "monit"
  notify:
    - restart rrdcached

- name: Créer repertoire collectd
  file: path=/etc/collectd/collectd.conf.d/ state=directory owner=root group=root mode="u+rwX,g+rwX,o+r" recurse=yes

- name: Copie des fichier de configuration
  copy: src={{ item }} dest=/etc/collectd/{{ item }} owner=root group=root mode="u+rw,g+r,o+r"
  with_items:
    - collectd.conf
    - collectd.conf.d/cpu.conf
    - collectd.conf.d/df.conf
    - collectd.conf.d/entropy.conf
    - collectd.conf.d/load.conf
    - collectd.conf.d/memory.conf
    - collectd.conf.d/swap.conf
    - collectd.conf.d/syslog.conf
    - collectd.conf.d/uptime.conf
    - collectd.conf.d/users.conf
  notify:
    - restart collectd

- name: collectd config
  replace: dest=/etc/collectd/collectd.conf regexp='^#Hostname "localhost"$' replace='Hostname "{{ ansible_hostname }}"' backup=no
  notify:
    - restart collectd

- name: Copie des fichier de configuration collectd network
  template: src=network.j2 dest=/etc/collectd/collectd.conf.d/network.conf owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart collectd

- name: Copie du fichier auth_file
  copy: src=secured/auth_file dest=/etc/collectd/auth_file owner=root group=root mode="u+rw,g+r,o+r"
  notify:
    - restart collectd
  when: ansible_hostname == "monit"

- name: Activer le service collectd au démérage
  service: name=collectd state=started enabled=yes

- name: Activer le service rrdcached au démérage
  service: name=rrdcached state=started enabled=yes
  when: ansible_hostname == "monit"
