---
# role commun de tout les hosts


- include: repos.yml
- include: users.yml
- include: monit.yml
- include: openssh.yml
- include: motd.yml
- include: resolv.yml
- include: collectd.yml
- include: ssmtp.yml
  when: ansible_hostname != "mail"
- include: local.yml
