---

- name: Installation de mlmmj
  apt: name=mlmmj state=present cache_valid_time=3600

- name: Ajout de l'user mlmmj
  user: name=mailing shell=/bin/false append=yes state=present uid=5050

- name: cron mlmmj
  cron: name="check mailing" hour="*/2" job="find /home/mailing/list -mindepth 1 -maxdepth 1 -type d -exec /usr/bin/mlmmj-maintd -F -d {} \;"

- name: Créer repertoire mlmmj
  file: path=/home/mailing/list state=directory owner=mailing group=mailing mode="u+rwX,g+rwX,o+r" recurse=yes
