---

- name: Installation de openssl, python, busybox
  apt: name={{ item }} state=present cache_valid_time=3600
  with_items:
    - openssl
    - python
    - busybox

- name: Ajout de l'user
  user: name=letsencrypt shell=/bin/false append=yes state=present uid=999

- name: Créer repertoire letsencrypt
  file: path=/home/letsencrypt/{{ item }} state=directory owner=letsencrypt group=letsencrypt mode="u+rwX,g+rwX,o+r" recurse=yes
  with_items:
    - bundles
    - ssl
    - webroot

- name: Copie des fichier
  copy: src={{ item }} dest=/home/letsencrypt/{{ item }} owner=letsencrypt group=letsencrypt mode="u+rx,g-rw,o-rwx"
  with_items:
    - le-cron.sh
    - acme_tiny.py

- name: Copie des fichier letsencrypt.key
  copy: src=secured/letsencrypt.key dest=/home/letsencrypt/ssl/letsencrypt.key owner=letsencrypt group=letsencrypt mode="u+rx,g-rw,o-rwx"

- name: Copie des fichier dh4096.pem
  copy: src=secured/dh4096.pem dest=/home/letsencrypt/ssl/dh4096.pem owner=letsencrypt group=letsencrypt mode="u+rx,g-rw,o-rwx"

- name: Copie des fichier supervisor
  copy: src=letsencrypt.conf dest=/etc/supervisor/conf.d/letsencrypt.conf owner=root group=root mode="u+rx,g+rx,o+r"
  notify:
    - restart supervisor

- name: cron letsencrypt
  cron: name="check certificates" minute="30" hour="4" job="/home/letsencrypt/le-cron.sh"

